Support Folia - Branch develop
SkytAsul/BeautyQuests pull request #314
Opened 2024-03-11 00:29 UTC by Euphillya

Change all schedulers using Energie
Use PaperLib to fix player teleportation

Please report any possible bugs arising from this patch.

Changement de toutes les schedulers en utilisant Energie
Utiliser PaperLib pour fixer la téléportation des joueurs

Merci de me soumettre tout possible bug provenant de ce patch.

2024-03-12 11:04 UTC, SkytAsul requested changes

2024-03-12 11:08 UTC, SkytAsul commented
Globalement, je ne comprend pas pourquoi tu dois _obligatoirement_ passer par le callback pour récupérer une instance de la tâche. Normalement, toutes les méthodes de type `scheduleTask` devraient renvoyer la tâche. C'est comme ça que fonctionnent les APIs de Spigot et de Folia.

2024-03-12 15:45 UTC, Euphillya commented
> Et est-ce que tu penses que tu pourrais intégrer la méthode `teleportAsync` dans ton API Energie ? J'aimerais bien ne pas avoir à shade 2 nouvelles librairies, dont une qui ne servirait qu'à une seule méthode...

Non car ce n'est pas le but de la lib, par contre, j'ai donc juste fait une exception avec NoSuchMethodError pour que les version après la 1.13.2 (paper) et 1.14 (spigot) puisse utiliser le tpAsync, sinon on utilise le sync.

2024-03-12 17:06 UTC, Euphillya commented on core/src/main/java/fr/skytasul/quests/BeautyQuests.java
> +				if (!Energie.isFolia()) launchUpdateChecker(pluginVersion);
Car UpdateChecker utilise les events de Bukkit, qui ne sont pas supporté par Folia

2024-03-17 11:08 UTC, SkytAsul requested changes
On est presque good je pense

2024-03-17 11:08 UTC, SkytAsul commented on core/src/main/java/fr/skytasul/quests/rewards/TeleportationReward.java
> +		QuestsPlugin.getPlugin().getScheduler().runTask(SchedulerType.SYNC, player, taskPlayer -> {
Why run this synchronously if it is to call async method?

2024-03-17 11:08 UTC, SkytAsul commented on core/src/main/java/fr/skytasul/quests/utils/QuestUtils.java
> +		QuestsPlugin.getPlugin().getScheduler().runTask(SchedulerType.SYNC, schedulerTaskInter -> run.run());
Unused lambda parameter such as `schedulerTaskInter` should be named `__`. This is valid for the whole PR.

2024-03-17 11:08 UTC, SkytAsul commented on core/src/main/java/fr/skytasul/quests/utils/logger/LoggerHandler.java
> +	private SchedulerRunnable scheduledFuture;
Naming?

2024-03-17 11:08 UTC, SkytAsul commented on core/src/main/java/fr/skytasul/quests/utils/logger/LoggerHandler.java
> +		if (scheduledFuture.getRunnable() != null) return;
You need to check for `scheduledFuture` to be null, not the inner runnable.

2024-03-17 11:08 UTC, SkytAsul commented on core/src/main/java/fr/skytasul/quests/utils/logger/LoggerHandler.java
> +		scheduledFuture.getRunnable().run();
See my comment on SchedulerRunnable.

2024-03-17 11:09 UTC, SkytAsul commented on core/src/main/java/fr/skytasul/quests/BeautyQuests.java
> +				if (!Energie.isFolia()) launchUpdateChecker(pluginVersion);
Je veux dire, il faut mettre un commentaire dans le code parce que ce n'est pas trivialement compréhensible.

2024-03-17 11:48 UTC, Euphillya commented on core/src/main/java/fr/skytasul/quests/rewards/TeleportationReward.java
> +		QuestsPlugin.getPlugin().getScheduler().runTask(SchedulerType.SYNC, player, taskPlayer -> {
Car ce n'est pas une tache Asynchrone qu'il faut

2024-03-17 11:59 UTC, Euphillya commented on api/src/main/java/fr/skytasul/quests/api/utils/SchedulerRunnable.java
On ne peut pas car on n'a pas la possibilité avec Folia, vu que ScheduledTaskInter fait une ré-implémentation des Planificateurs de Bukkit et de Folia sans les casser. Surtout que même si je le ferais, faudrait réutiliser toutes les possibilités qui existe avec Folia, qui deviendrait un gros bloc où la maintenabilité serait fortement réduite.

2024-03-17 13:20 UTC, SkytAsul commented on api/src/main/java/fr/skytasul/quests/api/utils/SchedulerRunnable.java
Tu pourrais stocker dans l'instance `SchedulerTaskInter` le callback associé lors de la création de la task via ton `Scheduler`. Ensuite, la méthode `run()` dans la task appellerait simplement le callback. Ça rajoute peu de code, et rien qui ne dépende de l'implémentation Folia ou legacy, c'est tout dans ta couche d'abstraction. Je peux faire une PR si tu veux.

2024-03-17 17:42 UTC, Euphillya commented on api/src/main/java/fr/skytasul/quests/api/utils/SchedulerRunnable.java
> Tu pourrais stocker dans l'instance `SchedulerTaskInter` le callback associé lors de la création de la task via ton `Scheduler`. Ensuite, la méthode `run()` dans la task appellerait simplement le callback. Ça rajoute peu de code, et rien qui ne dépende de l'implémentation Folia ou legacy, c'est tout dans ta couche d'abstraction. Je peux faire une PR si tu veux.

Vu que je suis pas trop disponible, si possible que vous fassiez la PR.

2024-04-20 22:17 UTC, closed without merging