Added FancyNpcs integration
SkytAsul/BeautyQuests pull request #331
Opened 2024-08-03 18:11 UTC by OakLoaf

I haven't been able to test this because I don't have all of the dependencies maven installed. If there is anything immediately obvious that is missing please let me know. 

Also if someone would be able to compile this PR for me to test that'd be wonderful :)

2024-08-03 20:45 UTC, OakLoaf commented
Whilst I still haven't tested this exact jar I have made an addon jar that is working with the same code (Hence the fixes)

2024-08-04 07:22 UTC, SkytAsul requested changes
Apart from the small change and the questions I asked, it seems really good! I'll compile and test it asap.

2024-08-04 07:22 UTC, SkytAsul commented on integrations/src/main/java/fr/skytasul/quests/integrations/npcs/BQFancyNPCs.java
> +        return false;
Why?

2024-08-04 07:22 UTC, SkytAsul commented on integrations/src/main/java/fr/skytasul/quests/integrations/npcs/BQFancyNPCs.java
> +    public static class BQFancyNpcs implements BqInternalNpc {
I suggest to rename this inner class BQFancyNpc. As it represents a single npc, it should be singular.

2024-08-04 07:22 UTC, SkytAsul commented on integrations/src/main/java/fr/skytasul/quests/integrations/npcs/BQFancyNPCs.java
> +            return null;
FancyNpcs are not real entities on the world? They are fully packet-based?

2024-08-08 17:37 UTC, OakLoaf commented on integrations/src/main/java/fr/skytasul/quests/integrations/npcs/BQFancyNPCs.java
> +        return false;
FancyNpcs are packet based

2024-08-08 17:38 UTC, OakLoaf commented on integrations/src/main/java/fr/skytasul/quests/integrations/npcs/BQFancyNPCs.java
> +            return null;
Yep, fully packet-based

2024-08-08 17:40 UTC, OakLoaf commented on integrations/src/main/java/fr/skytasul/quests/integrations/npcs/BQFancyNPCs.java
> +    public static class BQFancyNpcs implements BqInternalNpc {
Adjusted in [5159ef8](https://github.com/SkytAsul/BeautyQuests/pull/331/commits/5159ef88fce36b98bcc36716d8b3b3e32e75f88d)

2024-08-09 07:29 UTC, SkytAsul commented
Seems good! I have compiled a version of BeautyQuests with this fix included, may I send it to you on Discord so you can test it?

2024-08-09 07:30 UTC, SkytAsul approved these changes

2024-08-11 09:32 UTC, OakLoaf commented
Sure, my discord is `@oakloaf`

2024-08-12 09:50 UTC, SkytAsul commented
I can't add you as a friend, your requests are closed :sweat_smile: can you add me (@skytasul) or come on my Discord server?

2024-08-13 22:58 UTC, OakLoaf commented
Is there anything else that needs doing regarding this one?

2024-08-14 08:45 UTC, SkytAsul commented
Nah it's completely fine, I'll merge soon.

2024-08-25 19:56 UTC, merged

2024-08-25 19:57 UTC, SkytAsul commented
Thank you very much for the PR :)